---

- name: command | get VirtualBox version
  command: cat /home/vagrant/.vbox_version
  register: virtualbox_version

- name: mount | mount VirtualBox guest additions ISO
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: apt | install build dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: build_dependencies

- name: command | run VirtualBox guest additions installation
  command: sh /tmp/vbox/VBoxLinuxAdditions.run
  failed_when: false

- name: apt | uninstall build dependencies
  apt:
    name: "{{ item }}"
    purge: true
    state: absent
  with_items: build_dependencies

- name: mount | unmount VirtualBox guest additions ISO
  mount:
    name: /tmp/vbox
    src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
    state: unmounted
    fstype: iso9660
